### PR TITLE
FIX: SCN and SCCNN breaking after TopoNetX code change on the up laplacian

### PR DESCRIPTION
**Pull request by ninamiolane**
…p laplacian on simplicial complexes yet

### CODE REVIEW

**Review by ffl096 — APPROVED** [review]

**Comment by ffl096** [comment]
Thanks for the fix, this was still on my to-do! I'll merge once tests have completed :)

**Comment by ninamiolane** [comment]
@ffl096 Awesome! This PR is only a quick fix, the better fix would be to allow 'weights' to be passed for the up laplacian: is this on your todo?

**Comment by ffl096** [comment]
Weights are not implemented at all in TopoNetX yet. I think that would be a larger tasks that I don't have time to work on right now. If nobody else picks this up in lets say two weeks, I can take a look at it.

For context: Before pyt-team/TopoNetX#242, the `weight` parameter was just silently ignored. The laplacian matrix never was weighted.

**Comment by ninamiolane** [comment]
Goooot it! Yes, I was wondering why the up laplacian was the only neighborhood structure for which it was failing. Good idea to keep track of this.

**Pull request merged**
