### PR TITLE
Implementation of CWN

### PR DESCRIPTION
**Pull request by gvbazhenov**
Initial commit of CWN implementation for the ICML 2023 Topological Deep Learning Challenge

### CODE REVIEW

**Comment by gvbazhenov** [comment]
@michaelschaub @ffl096 Hello! Thank you for an opportunity to take part in the Topological Deep Learning Challenge! Our team is implementing `CWNLayer`, and we would appreciate your help since we have been facing some difficulties.

1. The [message passing scheme](https://github.com/awesome-tnns/awesome-tnns/blob/main/Cellular_Complexes.md#cw-network-cwn-1) involves messages and aggregations in a general form and covers a broad range of functions. We are not sure what is the recommended way to implement them. In particular, should we allow users to pass the message and aggregation methods as arguments into `CWNLayer`?
2. What is the recommended way to deal with several kinds of messages in one layer? In your tutorials, it is handled by instantiating `Conv` class for each message. However, CWN involves general messages, so `Conv` class is not suitable for us. Exactly the same problem applies to the `MessagePassing` class — the [API](https://pyt-team.github.io/topomodelx/api/base.html#topomodelx.base.message_passing.MessagePassing) tells *"This class should not be instantiated directly, but rather inherited through subclasses that effectively define a message passing function."* It means that we can not instantiate this class inside our layer. At the same time, we can not inherit our `CWNLayer` from `MessagePassing` because it handles only one type of message.
3. More specifically, the message $m_{y \rightarrow \{z\} \rightarrow x}^{(r \rightarrow r' \rightarrow r)} = M_{\mathcal{L}\uparrow}(h_x^{t,(r)}, h_y^{t,(r)}, h_z^{t,(r')})$ has three inputs. But the `forward` method of `MessagePassing` takes only `x_source` and `x_target`. Hence, it is impossible to implement a more general type of message passing using the existing API. Could you change it somehow so that it provides more freedom in which functions it can model and what objects it can operate on? We are ready to take part in solving this problem.

**Comment by USFCA-MSDS** [comment]
> 

Aggregation of multiple targets to a single source can be realized as a consecutive application of a merge nodes.

Suppose that you have a target signal x_t that you want to update given multiple neighborhood functions (matrices). The sources are specified using the matrix B1,...,Bk.  All matrices have target same as x_t and have source signals y_1,...,y_k respectively. 

Now the usual message passing can be used to aggregate messages for each individual source y_l to x_t,

So now you have messages that can have been sent from y_l to x_t using the class https://github.com/pyt-team/TopoModelX/blob/dev/topomodelx/nn/message_passing.py  for every 0<l<=k. 

The merge node (example implemented here : https://github.com/pyt-team/TopoModelX/blob/dev/topomodelx/nn/cxin_conv.py ) can be then use to aggregate messages obtained using different sources . Please let me know if that makes sense.

**Comment by mhajij** [comment]
> > 
> 
> Aggregation of multiple targets to a single source can be realized as a consecutive application of a merge nodes.
> 
> Suppose that you have a target signal x_t that you want to update given multiple neighborhood functions (matrices). The sources are specified using the matrix B1,...,Bk. All matrices have target same as x_t and have source signals y_1,...,y_k respectively.
> 
> Now the usual message passing can be used to aggregate messages for each individual source y_l to x_t,
> 
> So now you have messages that can have been sent from y_l to x_t using the class https://github.com/pyt-team/TopoModelX/blob/dev/topomodelx/nn/message_passing.py for every 0<l<=k.
> 
> The merge node (example implemented here : https://github.com/pyt-team/TopoModelX/blob/dev/topomodelx/nn/cxin_conv.py ) can be then use to aggregate messages obtained using different sources . Please let me know if that makes sense.

merge nodes are introduced here : 

https://[arxiv.org/pdf/2206.00606.pdf](https://arxiv.org/pdf/2206.00606.pdf)

implementation in the special case is here : 

https://github.com/pyt-team/TopoModelX/blob/dev/topomodelx/nn/cxin_conv.py

note that the above merge implementation can merge two targets to a single source, the general function you are looking for can be realized with this function : 

https://github.com/pyt-team/TopoModelX/blob/4bb096c947d68c7e702a6675e366f5ceba3df038/topomodelx/nn/cxin_conv.py#L299

**Comment by gvbazhenov** [comment]
@mhajij Thanks for your response! As we understand, your comment refers to the problem of aggregating various messages from different sources into one target domain. However, none of our questions is related to this problem. 

1. In fact, the first question is about a too general form of messages in CWN, so we are not sure if we should implement a particular variant of CWN (such as CIN, which has been proposed by the authors of CWN) or allow users to pass their custom message functions via arguments in the `__init__` method of our class.

2. As for the second question, here we explain that, due to the aforementioned problem of too general messages, `MessagePassing` is the only class that is suitable for constructing the second message $m_{y \rightarrow x}^{(r'' \rightarrow r)} = M_{\mathcal{B}}(h_x^{t,(r)}, h_y^{t,(r'')})$ of CWN. However, the existing API says that this class should not be instantiated directly, so it is not clear how we should instantiate this type of message in our implementation. However, we have found a note on the site of challenge saying that *in the case that `{Name of model}Layer` requires further manipulation of the computational primitives in `topomodelx/base`, a Pull Request may include modifications to the files in `topomodelx/base` or new files in topomodelx/base*. This note should resolve our second question.

3. Finally, in the third question, we try to point at the problem that none of the message passing classes in the existing API supports the processing of intermediate representations `h_z` on a par with target representations `h_x` and source representations `h_y`, which is required in the first message $m_{y \rightarrow \{z\} \rightarrow x}^{(r \rightarrow r' \rightarrow r)} = M_{\mathcal{L}\uparrow}(h_x^{t,(r)}, h_y^{t,(r)}, h_z^{t,(r')})$ of CWN. However, this question also might be resolved for the same reason as the previous one, since we may inherit from `MessagePassing` in a distinct file and modify the `message` method of our class to make it more flexible.

Thus, our only question is the first one — who is responsible for the implementation of a particular message function? We may consider a solution when users properly define their message functions and pass them into the arguments of `__init__` method, while we only use these functions in our implementation of message passing. Of course, we should create some default message functions (e.g., based on CIN) so that users can pass nothing to `CWNLayer`. Is this solution acceptable?

**Comment by mhajij** [comment]
> @mhajij Thanks for your response! As we understand, your comment refers to the problem of aggregating various messages from different sources into one target domain. However, none of our questions is related to this problem.
> 
> 1. In fact, the first question is about a too general form of messages in CWN, so we are not sure if we should implement a particular variant of CWN (such as CIN, which has been proposed by the authors of CWN) or allow users to pass their custom message functions via arguments in the `__init__` method of our class.

You are right, but in order to implement that, you do need my answer above. I tried to implement the merge node here 👍 
https://github.com/pyt-team/TopoModelX/blob/dev/topomodelx/nn/merge.py

Effectively this the same as sending messages as CWN/CXN. See Theorem 6.2 :  https://arxiv.org/pdf/2206.00606.pdf

In summary : merge node can realize the general message passing paradigm. 

You can think about a merge node as sending the node x_target receives messages from two different places x_source1 and x_source2. The way to send the message is via the maps G1 and G2 in the implementation above. The linear functions are needed in order to make the dimensionality match when concatenating the messages on the target. 



> 2. As for the second question, here we explain that, due to the aforementioned problem of too general messages, `MessagePassing` is the only class that is suitable for constructing the second message my→x(r″→r)=MB(hxt,(r),hyt,(r″)) of CWN. However, the existing API says that this class should not be instantiated directly, so it is not clear how we should instantiate this type of message in our implementation. We have found a note on the site of challenge saying that _in the case that `{Name of model}Layer` requires further manipulation of the computational primitives in `topomodelx/base`, a Pull Request may include modifications to the files in `topomodelx/base` or new files in topomodelx/base_. This note should resolve our second question.

The MessagePassing class is still not the most general form that we need it to be. Feel free to adjust it in your implemenation as given in the instructions.
> 3. Finally, in the third question, we try to point at the problem that none of the message passing classes in the existing API supports the processing of intermediate representations `h_z` on a par with target representations `h_x` and source representations `h_y`, which is required in the first message my→z→x(r→r′→r)=ML↑(hxt,(r),hyt,(r),hzt,(r′)) of CWN. However, this question also might be resolved for the same reason as the previous one, since we may inherit from `MessagePassing` in a distinct file and modify the `message` method of our class to make it more flexible.

Sounds good.
> 
> Thus, our only question is the first one — who is responsible for the implementation of a particular message function? We may consider a solution when users properly define their message functions and pass them into the arguments of `__init__` method, while we only use these functions in our implementation of message passing. Of course, we should create some default message functions (e.g., based on CIN) so that users can pass nothing to `CWNLayer`. Is this solution acceptable?

The only reason I pointed to CXIN implementation is to show you an example of how to merge signals from two different sources which is equivalent to message passing as described in CWN (in the special case of CIN). 

The above merge class can be used along with the HigherORderMessagePassing to implement a general message passing function.
The merge node is in a sense the dual of a message passing as described in CWN : in the message passing paradim you think about the source x and other neighbors are sending thier signals to that source. This is an update rule.
In the merge node it is easier to think about it as a functional rule : start where you want to send the message from (the neighbors of the source x) say you have two targets : these targers send thier messages via two operators G1 and G2.  Please read 6.3 : https://arxiv.org/pdf/2206.00606.pdf

**Comment by mathildepapillon** [comment]
Hello @gvbazhenov  ! Thank you for your submission. As we near the end of the challenge, I am collecting participant info for the purpose of selecting and announcing winners. Please email me (or have one member of your team email me) at papillon@ucsb.edu so I can share access to the voting form. In your email, please include:

- your first and last name (as well as any other team members)
- the title of the model you implemented
- the domain of the model you implemented
- your pull request number (#115)

Before July 13, make sure that your submission respects all Submission Requirements laid out on the challenge [page](https://pyt-team.github.io/topomodelx/challenge/index.html). Any submission that fails to meet this criteria will be automatically disqualified.

**Comment by gvbazhenov** [comment]
@mhajij Thank you very much for this discussion! We have managed to implement the CWN layer and hopefully made it clear to use and flexible to extend for user needs. Our PR is now ready for review.

**Pull request merged**
