### PR TITLE
Fixing Issues with thumbnails and API Reference Docs

### PR DESCRIPTION
**Pull request by devendragovil**
Fixing thumbnail issue #169 

Also making progress in resolving #165  API Reference display

### CODE REVIEW

**Comment by ninamiolane** [comment]
Awesome, thanks for this! For the thumbnails, it might be better to use the tensor diagrams of the NNs, such as the one from the screenshot. What do you think? I'm scared that the equations would not look as good as thumbnails.


Screen Shot 2023-08-29 at 3 00 13 PM

Tensor diagrams can be found here: https://arxiv.org/pdf/2304.10031.pdf

**Comment by devendragovil** [comment]
I heartily agree, I just wanted to have something to test if the code works. I will update the images by EOD with the diagrams.

**Comment by ninamiolane** [comment]
Awesome, thanks for the quick answer! I can share the .svg or the .pdf of the figure with the tensor diagrams via email, if you want to be able to screenshot the diagrams easily.

**Comment by devendragovil** [comment]
Oh yeah, that would be awesome. You can mail me at govildev@gmail.com. Thanks a lot!

**Comment by ninamiolane** [comment]
@devendragovil I'm converting to drafty for now, I'll let you mark it ready for review when you'd like a review. Thanks for everything!

**Review by mhajij — APPROVED** [review]

**Pull request merged**
