### PR TITLE
Fixes #169, Thumbnails Updated

### LINKED ISSUE #169: Add tutorials' thumbnails on TopoModelX doc website
# What?

The tutorials webpage of TopoModelX documentation website does not display any thumbnails.

https://pyt-team.github.io/topomodelx/tutorials/index.html

We should add thumbnails.

# Why?

The tutorials webpage is one of the first pages that users see. It should look clean.

Additionally, thumbnails help the reader understanding what the tutorials are about.

# Where and How?

In order to add thumbnails, we refer to the similar github issue that added thumbnails for the tutorials of TopoNetX:
https://github.com/pyt-team/TopoNetX/issues/84

The PR solving the issue was:
https://github.com/pyt-team/TopoNetX/pull/179

The persons solving the issue were: @devendragovil and @mhajij: ask them for guidelines if needed.

For each tutorial notebook:
1. Locate the tensor diagram corresponding to the neural network implemented in the notebook in [Fig. 11](https://github.com/pyt-team/TopoModelX/blob/main/topomodelx.jpeg) of the review [Architectures of Topological Deep Learning: A Survey of Topological Neural Networks](https://arxiv.org/pdf/2304.10031.pdf).
2. Crop the tensor diagram out of the figure.
3. Make this tensor diagram the thumbnail of the notebook.

### PR DESCRIPTION
**Pull request by devendragovil**
Updated the thumbnails with tensor diagrams as suggested in #169

### CODE REVIEW

**Comment by ninamiolane** [comment]
@devendragovil Thanks!! And thanks for being that fast.

For some of them, the cropping is not very clean: parts of the neighboring tensor diagrams appear. I will send you the .svg version of the figure via email, so that you can crop only the diagram for each thumbnail.

Then we can merge!

**Comment by devendragovil** [comment]
@ninamiolane 
I have detailed all the issues that I observed in #169 in a comment [here](https://github.com/pyt-team/TopoModelX/issues/169#issuecomment-1709436104).

Having SVG files would be awesome for quality and clarity. 

Reproducing the previous comment below:

I have updated the thumbnails with tensor diagrams, I came across the following issues though:

1. Same Tensor Diagram: There are multiple notebooks for (seemingly) same model. These include, examples:
    a. can_train_bis and can_train
    b. allset_train and allset_transformer_train
    c. hnhn_train_bis and hnhn_train
2. Unavailable Model Tensor:
    a. Can't find any model named ccxn (for ccxn_train) in [Fig 11](https://github.com/pyt-team/TopoModelX/blob/main/topomodelx.jpeg). However the notebook is about Hajij (2020) so I used tensor diagram for cxn Hajij (2020)
    b. template_train notebook in Hypergraph (As of now thumbnail is a generic hypergraph)
3. Multiple tensor diagrams: Some models have multiple tensor diagrams like CXN, Hajij (2020), HSN Hajij22b
4. No clear screenshot: I was unable to take clear screenshots for some models due to encroachment of nearby tensor diagrams. @ninamiolane Wanted your opinion. Are the current thumbnails acceptable or should I also edit them? Example:
    a. CWN, Bodnar21b
    b. Dist2Cycle, Keros22
    c. SAN, Giusti22a
5. Curious case of sccn_train: There is no sccn tensor diagram, however there is a scnn and the notebook of sccn seems to be pointing to the same author, year combination (Yang 22). However, there is another notebook with scnn. For now, sccn_train has thumbnail for scnn.
6. There is scn2_train. Is it the same as scn?
7. Scone_train_bis notebook seems to be referring to HSN Hajij 22, rather than the roddenberry paper. For now, both scone_train_bis and scone_train have the same tensor diagram

**Comment by mhajij** [comment]
> 2\. a. Can't find any model named ccxn (for ccxn_train) in [Fig 11](https://github.com/pyt-team/TopoModelX/blob/main/topomodelx.jpeg). However the notebook is about Hajij (2020) so I used tensor diagram for cxn Hajij (2020)

@ninamiolane , it might be a good idea to give @devendragovil the original CSV file to extract the TD from the file immediately.

**Comment by ninamiolane** [comment]
@devendragovil I've answered on the issue + shared the editable Fig 11 via email.
@mhajij definitely: done! ✔️

**Comment by ninamiolane** [comment]
@devendragovil converting to draft for now. Let me know when it's ready?

Side note: can_bis and scone_bis do not exist anymore. You can remove anything related to them. Thanks!

**Comment by devendragovil** [comment]
The latest changes help resolve #169 and #162. 

@ninamiolane  Requesting your review.

**Review by ninamiolane — APPROVED** [review]
Fantastic!! Thank you so much.

**Pull request merged**
